### ISSUE TITLE
The model on target task should be fined-tuned on the basis of BERT or MoEBERT?

### ISSUE THREAD

**Issue by LisaWang0306** [SimiaoZuo/MoEBERT#1]
In README, you mentioned that:
> Before running any distillation code, a pre-trained BERT model should be fine-tuned on the target task. Path to the fine-tuned model should be passed to `--model_name_or_path`.
Can I fine-tune on `bert-base-uncased` model and run distillation code with MoE options?
Is pretrained MoEBERT model necessary?
Thanks very much!

**Comment by SimiaoZuo** [comment]
For example, suppose we are working on the MNLI dataset. We first fine-tune a pre-trained BERT model (e.g., bert-base-uncased) on MNLI, and this fine-tuned model serves as the teacher.

**Comment by LisaWang0306** [comment]
Thanks!

**Comment by CaffreyR** [comment]
Hi @LisaWang0306 , may I ask that how to get the finetune model as you mentioned in `bert-base-uncased`! Many thanks!
